name: Tests

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    env:
      TEST: "false"

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn and dependencies
        run: npm install -g yarn && yarn

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Solhint linter
        run: npx solhint "src/*.sol"

      - name: Test
        run: yarn test
